# App Server Config
server:
  #端口号
  port: 10100
  #项目名，如果不设定，默认是 /
  context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

# Config
spring:
  application:
    name: idev-gateway # 在eureka中此值作为vipaddress,在发现服务时使用