# App Server Config
server:
  #端口号
  port: 10100
  #项目名，如果不设定，默认是 /
  context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

# Config
spring:
  application:
    name: idev-gateway # 在eureka中此值作为vipaddress,在发现服务时使用
  cloud:
      gateway:
        routes:
        - id: idev_route
          uri: http://localhost:10100/
          predicates:
          - Path=/idev
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
            - name: iDevHystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG